# Specify analysis options.
include: package:pedantic/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    todo: ignore
    deprecated_member_use_from_same_package: ignore
    # deprecated_member_use: ignore
    sdk_version_async_exported_from_core: ignore
    invalid_assignment: ignore
    argument_type_not_assignable: ignore
    non_bool_negation_expression: ignore
    non_bool_condition: ignore
    non_bool_operand: ignore
    missing_return: error
    dead_code: info
    use_full_hex_values_for_flutter_colors: ignore
    implementation_imports: ignore

  exclude:
    - "bin/cache/**"
    # the following two are relative to the stocks example and the flutter package respectively
    # see https://github.com/dart-lang/sdk/issues/28463
    - "lib/i18n/messages_*.dart"
    - "lib/src/http/**"
    - "lib/plugins/pdf_viewer/lib/src/**"
    - "lib/plugins/pdf_viewer/lib/**"
    - "generated_plugin_registrant.dart"
    # - "test/**"
    - "test_driver/**"
    - "integration_test/**"

linter:
  rules:
    await_only_futures: false
    avoid_shadowing_type_parameters: false
    avoid_types_on_closure_parameters: true
    avoid_void_async: true
    avoid_null_if: false
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    constant_identifier_names: true
    control_flow_in_finally: true
    directives_ordering: true
    empty_statements: true
    hash_and_equals: true
    implementation_imports: true
    non_constant_identifier_names: false
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    test_types_in_equals: false
    throw_in_finally: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_statements: true
    avoid_null_if: false
